In [1]:
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}
def on_button_press(p):
    print('Введите команду: ')
    # p = str(input())
    print(p)
    if p == 'p':
        print('Введите номер документа: ')
        doc = (input())
        print(doc)
        flag = True
        for key in documents:
            #print(key)
            if doc == key['number']:
                print(key['name'])
                flag = False
        if flag:
            print('Не найдено')
    else:
        print('Человека нет')
    return p

p = str(input())
on_button_press(p)



Введите команду: 
p
Введите номер документа: 
11-2
Геннадий Покемонов


'p'

Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

перечень всех документов
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}

Пункт 1. Пользователь по команде "p" может узнать владельца документа по его номеру
Примеры работы:

Введите команду:
p

Введите номер документа:
10006
Результат:
Владелец документа: Аристарх Павлов

Введите команду:
p

Введите номер документа:
12345
Результат:
Документ не найден в базе

In [2]:
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}

def on_button_press(s):
    print('Введите команду: ')
    #s = str(input())
    print(s)
    if s == 's':
        print('Введите номер документа: ')
        doc = (input())
        print(doc)
        flag = True
        for key, value in directories.items():
            #print(key)
            if doc in value:
                print(f'Документ на полке {key}')
                flag = False
        if flag:
            print('Не найдено')
    else:
        print('Человека нет')
    return s

s = str(input())
on_button_press(s)

Введите команду: 
s
Введите номер документа: 
11-2
Документ на полке 1


's'

Пункт 2. Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится
Примеры работы:

Введите команду:
s

Введите номер документа:
10006
Результат:
Документ хранится на полке: 2

Введите команду:
s

Введите номер документа:
12345
Результат:
Документ не найден в базе

In [20]:
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}

def on_button_press(l):
    print('Введите команду: ')
    #l = str(input())
    print(l)
    if l == 'l':
        for libr in documents:
            t = libr['type']
            num = libr['number']
            name = libr['name']
            for key, value in directories.items():
                if num in value:
                    shelf = str(key)
            print(f'№: {num}, тип: {t}, владелец: {name}, полка {shelf}')   
    else:
        print('Ошибка')
    return l

l = str(input())
on_button_press(l)

Введите команду: 
l
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка 2


'l'

Пункт 3. Пользователь по команде "l" может увидеть полную информацию по всем документам
Пример работы:

Введите команду:
l
Результат:

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [22]:
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}

def on_button_press(ads):
    print('Введите команду: ')
    #ads = str(input())
    print(ads)
    if ads == 'ads':
        print('Введите номер полки: ')
        shelf = input()
        if shelf not in directories.keys():
            directories[shelf] = []
            print('Полка добавлена. Текущий перечень полок:', f'{[key for key in directories.keys()]}')
        else:
            print('Полка существует. Текущий перечень полок:', f'{[key for key in directories.keys()]}')
    else:
        print('Ошибка')
    return ads

ads = str(input())
on_button_press(ads)

Введите команду: 
ads
Введите номер полки: 
Полка добавлена. Текущий перечень полок: ['1', '2', '3', 12]


'ads'

Пункт 4. Пользователь по команде "ads" может добавить новую полку
Примеры работы:

Введите команду:
ads

Введите номер полки:
10
Результат:
Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.

Введите команду:
ads

Введите номер полки:
1
Результат:
Такая полка уже существует. Текущий перечень полок: 1, 2, 3.

In [24]:
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}

def on_button_press(ds):
    print('Введите команду: ')
    #ds = str(input())
    print(ds)
    if ds == 'ds':
        print('Введите номер полки: ')
        shelf = input()
        if directories[shelf] == []:
            directories.pop(shelf)
            print('Полка удалена. Перечень полок: ', f'{[key for key in directories.keys()]}')
        else:
            print('На полке есть документы, удалите их перед удалением полки. Текущий перечень полок: ', f'{[key for key in directories.keys()]}')
    else:
        print('Ошибка')
    return ds
 
ds = str(input())
on_button_press(ds)

Введите команду: 
ds
Введите номер полки: 
Полка удалена. Перечень полок:  ['1', '2']


'ds'

Пункт 5. Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)
Примеры работы:

Введите команду:
ds

Введите номер полки:
3
Результат:
Полка удалена. Текущий перечень полок: 1, 2.

Введите команду:
ds

Введите номер полки:
1
Результат:
На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.

Введите команду:
ds

Введите номер полки:
4
Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3.