In [11]:
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}

def on_button_press(ad):
    print('Введите команду: ')
    #ads = str(input())
    print(ad)
    if ad == 'ad':
        print('Введите номер документа: ')
        num = input()
        print(num)
        print('Введите тип документа: ')
        t = input()
        print(t)
        print('Введите владельца документа: ')
        name = input()
        print(name)
        print('Введите полку для хранения: ')
        shelf = input()
        print(shelf)
        if shelf in directories.keys():
            list = {}
            documents.insert(len(documents)+1, list)
            list['type'] = t
            list['number'] = num
            list['name'] = name
            print('Документ добавлен. Текущий список документов:')
            for libr in documents:
                t = libr['type']
                num = libr['number']
                name = libr['name']
                for key, value in directories.items():
                    if num in value:
                        shelf = str(key)
                print(f'№: {num}, тип: {t}, владелец: {name}, полка {shelf}')
        else:
            print('Полка не существует. Добавьте её командой as. Текущий список документов:')
            for libr in documents:
                t = libr['type']
                num = libr['number']
                name = libr['name']
                for key, value in directories.items():
                    if num in value:
                        shelf = str(key)
                print(f'№: {num}, тип: {t}, владелец: {name}, полка {shelf}')
    else:
        print('Ошибка')
    return ad

ad = str(input())
on_button_press(ad)

Введите команду: 
ad
Введите номер документа: 
qw
Введите тип документа: 
qw
Введите владельца документа: 
3
Введите полку для хранения: 
3
Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка 2
№: qw, тип: qw, владелец: 3, полка 2


'ad'

Пункт 1. Пользователь по команде "ad" может добавить новый документ в данные
Примеры работы:

Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
3
Результат:

Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
4
Результат:

Такой полки не существует. Добавьте полку командой as. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [53]:
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}

def on_button_press(d):
    print('Введите команду: ')
    #d = str(input())
    print(d)
    if d == 'd':
        print('Введите номер документа: ')
        n = input()
        print(n)
        if n != libr['number']:
            print('Документ не найден')
            for libr in documents:
                t =libr['type']
                num = libr['number']
                name = libr['name']
                for key, values in directories.items():
                    print(f'№: {num}, тип: {t}, владелец: {name}, полка {key}')
        elif n == libr['number']:
                documents.remove(libr)
                print('Документ удален. Текущий список:')
                for libr in documents:
                    t =libr['type']
                    num = libr['number']
                    name = libr['name']
                    for key, values in directories.items():
                        if n in values:
                            values.remove(n)
                    print(f'№: {num}, тип: {t}, владелец: {name}, полка {key}')
                           
    else:
        print('Ошибка')
    return documents

d = str(input())
documents = on_button_press(d)
print(documents)


Введите команду: 
d
Введите номер документа: 
11-2


UnboundLocalError: cannot access local variable 'libr' where it is not associated with a value

Пункт 2. Пользователь по команде "d" может удалить документ из данных
Примеры работы:

Введите команду:
d

Введите номер документа:
10006
Результат:

Документ удален. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
Введите команду:
d

Введите номер документа:
123456
Результат:

Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

In [66]:
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}



def on_button_press(m):
    if m == 'm':
        print('Ведите номер документа:')
        n = input()
        print(n)
        print('Ведите номер полки:')
        shelf = input()
        print(shelf)
        if shelf not in directories:
            return print('Полки не существует')
        for key, value in directories.items():
            if n in value:
                value.remove(n)
                directories[shelf].append(n)
                return print('Документ перемещен.', f'{directories}')
        return print('Документ не найден', f'{directories}')  
    else:
        print('Ошибка')
    return m

m = str(input())
on_button_press(m)

Ведите номер документа:
11-2
Ведите номер полки:
3
Документ перемещен. {'1': ['2207 876234'], '2': ['10006'], '3': ['11-2']}


Пункт 3. Пользователь по команде "m" может переместить документ с полки на полку
Примеры работы:

Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
3
Результат:

Документ перемещен. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 3
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
10
Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3.

Введите команду:
m

Введите номер документа:
42
Введите номер полки:
2
Результат:

Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2